// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TarlaAsistani.Infrastructure.Persistence;

#nullable disable

namespace TarlaAsistani.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905113046_AddCaseContextSnapshot")]
    partial class AddCaseContextSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.AccountDeletionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirebaseAuthDeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirebaseTokensRevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirebaseUidSnapshot")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("FirestoreAnonymizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MediaDeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PostgresAnonymizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingOwnerToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Status", "NextRetryAtUtc", "LeaseUntilUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_account_deletion_jobs_retry_schedule");

                    b.ToTable("account_deletion_jobs", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ActivityType")
                        .HasColumnType("text");

                    b.Property<float?>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClientOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("Cost")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CropPeriodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Manual");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Confirmed");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoiceTranscript")
                        .HasColumnType("text");

                    b.Property<string>("VoiceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("CropPeriodId");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("uq_activities_task_id")
                        .HasFilter("\"TaskId\" IS NOT NULL");

                    b.HasIndex("CreatedById", "ClientOperationId")
                        .IsUnique()
                        .HasDatabaseName("uq_activities_client_operation")
                        .HasFilter("\"ClientOperationId\" IS NOT NULL");

                    b.HasIndex("FarmId", "ArchivedAtUtc")
                        .HasDatabaseName("ix_activities_farm_archived");

                    b.HasIndex("FarmId", "OccurredAtUtc")
                        .HasDatabaseName("ix_activities_farm_occurred");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.ActivityRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ActivityId", "ChangedAtUtc")
                        .HasDatabaseName("ix_activity_revisions_activity_changed");

                    b.ToTable("activity_revisions", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("HasPhoto")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_ai_usage_logs_created");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_ai_usage_logs_user_created");

                    b.ToTable("ai_usage_logs", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseContextSnapshot", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CropGrowingDay")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CropHarvestedAt")
                        .HasColumnType("date");

                    b.Property<string>("CropName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("CropPlantedAt")
                        .HasColumnType("date");

                    b.Property<double?>("CurrentHumidityPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("CurrentTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FarmNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("IrrigationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsBasedOnStaleWeather")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Next24HoursPrecipitationMm")
                        .HasColumnType("double precision");

                    b.Property<string>("RecentActivitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("SizeInHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("SoilType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("WeatherFetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeatherProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CaseId");

                    b.ToTable("case_context_snapshots", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseMedia", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.HasKey("CaseId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("case_media", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Comment");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("CaseId", "CreatedAtUtc")
                        .HasDatabaseName("ix_case_messages_case_created");

                    b.ToTable("case_messages", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseMessageMedia", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("case_message_media", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.ClientOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "ClientOperationId")
                        .IsUnique()
                        .HasDatabaseName("uq_client_operations_actor_key");

                    b.HasIndex("ActorId", "CreatedAtUtc")
                        .HasDatabaseName("ix_client_operations_actor_created");

                    b.ToTable("client_operations", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CropPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CropType")
                        .HasColumnType("text");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("HarvestedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlantedAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Variety")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "PlantedAt")
                        .HasDatabaseName("ix_crop_periods_farm_planted");

                    b.HasIndex("FarmId", "Status")
                        .IsUnique()
                        .HasDatabaseName("uq_crop_periods_one_active_per_farm")
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("crop_periods", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "Active")
                        .HasDatabaseName("ix_device_tokens_user_active");

                    b.ToTable("device_tokens", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IrrigationMethod")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<double?>("SizeInHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("SoilType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "ArchivedAt")
                        .HasDatabaseName("ix_farms_owner_archived");

                    b.HasIndex("OwnerId", "Name")
                        .HasDatabaseName("ix_farms_owner_name");

                    b.ToTable("farms", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.FarmTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Medium");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CropPeriodId")
                        .HasColumnType("uuid");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotAppliedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("New");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ViewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CropPeriodId");

                    b.HasIndex("FarmId", "CreatedAtUtc")
                        .HasDatabaseName("ix_tasks_farm_created");

                    b.HasIndex("FarmId", "DueDate", "DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("uq_tasks_farm_due_dedupe");

                    b.HasIndex("FarmId", "DueDate", "Status")
                        .HasDatabaseName("ix_tasks_farm_due_status");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.FirebaseLinkApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("uq_firebase_link_approvals_one_unconsumed_per_uid")
                        .HasFilter("\"ConsumedAtUtc\" IS NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_firebase_link_approvals_one_unconsumed_per_user")
                        .HasFilter("\"ConsumedAtUtc\" IS NULL");

                    b.ToTable("firebase_link_approvals", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.MarketPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("ChangePercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PreviousPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("market_prices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Category = "Fuel",
                            ChangePercent = 1.47m,
                            Code = "DIESEL",
                            CurrentPrice = 44.85m,
                            Name = "Motorin (Mazot)",
                            PreviousPrice = 44.20m,
                            Source = "EPDK",
                            Unit = "TL/Lt",
                            UpdatedAtUtc = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Category = "Fuel",
                            ChangePercent = 0.00m,
                            Code = "GASOLINE",
                            CurrentPrice = 43.20m,
                            Name = "Benzin (95 Oktan)",
                            PreviousPrice = 43.20m,
                            Source = "EPDK",
                            Unit = "TL/Lt",
                            UpdatedAtUtc = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Category = "Fertilizer",
                            ChangePercent = -1.72m,
                            Code = "UREA",
                            CurrentPrice = 14250.00m,
                            Name = "Üre Gübresi (%46 N)",
                            PreviousPrice = 14500.00m,
                            Source = "GUBRETAS",
                            Unit = "TL/Ton",
                            UpdatedAtUtc = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Category = "Fertilizer",
                            ChangePercent = 0.00m,
                            Code = "DAP",
                            CurrentPrice = 20800.00m,
                            Name = "DAP Gübresi (18-46-0)",
                            PreviousPrice = 20800.00m,
                            Source = "GUBRETAS",
                            Unit = "TL/Ton",
                            UpdatedAtUtc = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Category = "Crop",
                            ChangePercent = 1.55m,
                            Code = "WHEAT",
                            CurrentPrice = 9850.00m,
                            Name = "Ekmeklik Buğday",
                            PreviousPrice = 9700.00m,
                            Source = "TURIB",
                            Unit = "TL/Ton",
                            UpdatedAtUtc = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Category = "Crop",
                            ChangePercent = -0.61m,
                            Code = "CORN",
                            CurrentPrice = 8200.00m,
                            Name = "Mısır (1. Sınıf)",
                            PreviousPrice = 8250.00m,
                            Source = "TURIB",
                            Unit = "TL/Ton",
                            UpdatedAtUtc = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Category = "Fx",
                            ChangePercent = 0.12m,
                            Code = "USD_TRY",
                            CurrentPrice = 34.2200m,
                            Name = "Dolar",
                            PreviousPrice = 34.1800m,
                            Source = "TCMB",
                            Unit = "TL",
                            UpdatedAtUtc = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Category = "Fx",
                            ChangePercent = -0.18m,
                            Code = "EUR_TRY",
                            CurrentPrice = 37.9500m,
                            Name = "Euro",
                            PreviousPrice = 38.0200m,
                            Source = "TCMB",
                            Unit = "TL",
                            UpdatedAtUtc = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("OwnerId", "CreatedAtUtc")
                        .HasDatabaseName("ix_media_assets_owner_created");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DeepLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_notifications_status_created");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_notifications_user_created");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("otp_codes", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.PilotFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RelatedCaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Open");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RelatedCaseId");

                    b.HasIndex("RelatedTaskId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("FeedbackType", "CreatedAtUtc")
                        .HasDatabaseName("ix_pilot_feedback_type_created");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_pilot_feedback_status_created");

                    b.ToTable("pilot_feedback", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.ProactiveAdvisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionRecommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdvisoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgronomicExplanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CropPeriodId")
                        .HasColumnType("uuid");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("DismissedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("RecommendedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("RelatedTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CropPeriodId");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_proactive_advisories_dedupe");

                    b.HasIndex("RelatedTaskId");

                    b.HasIndex("UserId", "IsDismissed")
                        .HasDatabaseName("ix_proactive_advisories_user_active");

                    b.HasIndex("FarmId", "IsDismissed", "ValidUntilUtc")
                        .HasDatabaseName("ix_proactive_advisories_farm_active");

                    b.ToTable("proactive_advisories", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FullName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Province")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.SupportCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedExpertId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedExpertId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FarmId", "CreatedAtUtc")
                        .HasDatabaseName("ix_support_cases_farm_created");

                    b.HasIndex("Status", "Priority")
                        .HasDatabaseName("ix_support_cases_status_priority");

                    b.ToTable("support_cases", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.WeatherSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId", "FetchedAtUtc")
                        .HasDatabaseName("ix_weather_snapshots_farm_fetched");

                    b.ToTable("weather_snapshots", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<string>("AnonymizedSubjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Farmer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnonymizedSubjectId")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.AccountDeletionJob", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("AccountDeletionJob")
                        .HasForeignKey("TarlaAsistani.Domain.Entities.AccountDeletionJob", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Activity", b =>
                {
                    b.HasOne("User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TarlaAsistani.Domain.Entities.CropPeriod", "CropPeriod")
                        .WithMany()
                        .HasForeignKey("CropPeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TarlaAsistani.Domain.Entities.Farm", "Farm")
                        .WithMany("Activities")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("CropPeriod");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.ActivityRevision", b =>
                {
                    b.HasOne("TarlaAsistani.Domain.Entities.Activity", "Activity")
                        .WithMany("Revisions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activity");

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.AiUsageLog", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseContextSnapshot", b =>
                {
                    b.HasOne("TarlaAsistani.Domain.Entities.SupportCase", "Case")
                        .WithOne("Context")
                        .HasForeignKey("TarlaAsistani.Domain.Entities.CaseContextSnapshot", "CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseMedia", b =>
                {
                    b.HasOne("TarlaAsistani.Domain.Entities.SupportCase", "Case")
                        .WithMany("MediaLinks")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarlaAsistani.Domain.Entities.MediaAsset", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseMessage", b =>
                {
                    b.HasOne("TarlaAsistani.Domain.Entities.SupportCase", "Case")
                        .WithMany("Messages")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseMessageMedia", b =>
                {
                    b.HasOne("TarlaAsistani.Domain.Entities.MediaAsset", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarlaAsistani.Domain.Entities.CaseMessage", "Message")
                        .WithMany("MediaLinks")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.ClientOperation", b =>
                {
                    b.HasOne("User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CropPeriod", b =>
                {
                    b.HasOne("TarlaAsistani.Domain.Entities.Farm", "Farm")
                        .WithMany("CropPeriods")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Farm", b =>
                {
                    b.HasOne("User", "Owner")
                        .WithMany("Farms")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.FarmTask", b =>
                {
                    b.HasOne("User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TarlaAsistani.Domain.Entities.CropPeriod", "CropPeriod")
                        .WithMany()
                        .HasForeignKey("CropPeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TarlaAsistani.Domain.Entities.Farm", "Farm")
                        .WithMany("Tasks")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("CropPeriod");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.FirebaseLinkApproval", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("FirebaseLinkApprovals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.MediaAsset", b =>
                {
                    b.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Notification", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.PilotFeedback", b =>
                {
                    b.HasOne("User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarlaAsistani.Domain.Entities.SupportCase", "RelatedCase")
                        .WithMany()
                        .HasForeignKey("RelatedCaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TarlaAsistani.Domain.Entities.FarmTask", "RelatedTask")
                        .WithMany()
                        .HasForeignKey("RelatedTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("RelatedCase");

                    b.Navigation("RelatedTask");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.ProactiveAdvisory", b =>
                {
                    b.HasOne("TarlaAsistani.Domain.Entities.CropPeriod", "CropPeriod")
                        .WithMany()
                        .HasForeignKey("CropPeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TarlaAsistani.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TarlaAsistani.Domain.Entities.FarmTask", "RelatedTask")
                        .WithMany()
                        .HasForeignKey("RelatedTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropPeriod");

                    b.Navigation("Farm");

                    b.Navigation("RelatedTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Profile", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("TarlaAsistani.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.SupportCase", b =>
                {
                    b.HasOne("User", "AssignedExpert")
                        .WithMany()
                        .HasForeignKey("AssignedExpertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TarlaAsistani.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedExpert");

                    b.Navigation("CreatedBy");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.WeatherSnapshot", b =>
                {
                    b.HasOne("TarlaAsistani.Domain.Entities.Farm", "Farm")
                        .WithMany("WeatherSnapshots")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Activity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.CaseMessage", b =>
                {
                    b.Navigation("MediaLinks");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CropPeriods");

                    b.Navigation("Tasks");

                    b.Navigation("WeatherSnapshots");
                });

            modelBuilder.Entity("TarlaAsistani.Domain.Entities.SupportCase", b =>
                {
                    b.Navigation("Context");

                    b.Navigation("MediaLinks");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("AccountDeletionJob");

                    b.Navigation("Farms");

                    b.Navigation("FirebaseLinkApprovals");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
