using System.Text.Json;

namespace TarlaAsistani.Application.Common.AI;

/// <summary>
/// Represents an invocation request for a tool generated by the AI model.
/// </summary>
public sealed record AIToolCall
{
    /// <summary>
    /// Gets the invocation identifier assigned to this tool call.
    /// May be empty if the underlying provider does not produce call IDs.
    /// </summary>
    public string CallId { get; init; }

    /// <summary>
    /// Gets the name of the tool to be executed.
    /// </summary>
    public string ToolName { get; init; }

    /// <summary>
    /// Gets the structured arguments passed to the tool as a <see cref="JsonElement"/>.
    /// </summary>
    public JsonElement Arguments { get; init; }

    /// <summary>
    /// Gets optional provider-specific metadata (e.g. opaque thought signature or session state)
    /// preserved across conversation turns.
    /// </summary>
    public IReadOnlyDictionary<string, string>? ProviderMetadata { get; init; }

    /// <summary>
    /// Initializes a new instance of <see cref="AIToolCall"/>.
    /// </summary>
    /// <param name="callId">The call identifier.</param>
    /// <param name="toolName">The name of the tool.</param>
    /// <param name="arguments">The structured JSON arguments.</param>
    /// <param name="providerMetadata">Optional opaque provider-specific metadata.</param>
    public AIToolCall(
        string? callId,
        string toolName,
        JsonElement arguments,
        IReadOnlyDictionary<string, string>? providerMetadata = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(toolName);

        CallId = callId ?? string.Empty;
        ToolName = toolName;
        Arguments = arguments;
        ProviderMetadata = providerMetadata;
    }

    /// <summary>
    /// Deserializes the tool arguments into a strongly-typed model.
    /// </summary>
    /// <typeparam name="T">The target type to deserialize into.</typeparam>
    /// <param name="options">Optional JSON serializer options.</param>
    /// <returns>The deserialized instance, or null if arguments represent JSON null.</returns>
    public T? DeserializeArguments<T>(JsonSerializerOptions? options = null)
    {
        if (Arguments.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)
        {
            return default;
        }

        return Arguments.Deserialize<T>(options);
    }

    /// <summary>
    /// Creates an <see cref="AIToolCall"/> from a raw JSON arguments string.
    /// </summary>
    public static AIToolCall Create(
        string? callId,
        string toolName,
        string? argumentsJson,
        IReadOnlyDictionary<string, string>? providerMetadata = null)
    {
        var rawJson = string.IsNullOrWhiteSpace(argumentsJson) ? "{}" : argumentsJson.Trim();
        using var document = JsonDocument.Parse(rawJson);
        return new AIToolCall(callId, toolName, document.RootElement.Clone(), providerMetadata);
    }
}
