using System.Net;
using System.Net.Http.Json;
using FluentAssertions;
using TarlaAsistani.API.Endpoints;
using TarlaAsistani.Application.Features.Tasks.DTOs;
using TarlaAsistani.Domain.Enums;
using TaskStatus = TarlaAsistani.Domain.Enums.TaskStatus;

namespace TarlaAsistani.IntegrationTests;

public class TaskEndpointsIntegrationTests : IClassFixture<CustomWebApplicationFactory>
{
    private readonly HttpClient _client;

    public TaskEndpointsIntegrationTests(CustomWebApplicationFactory factory)
    {
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task CreateFarmAndGetDailyTasks_ShouldAutoGenerateDailyCheckTasks()
    {
        // 1. Create Farm with active crop period
        var ownerId = Guid.NewGuid();
        var createRequest = new CreateFarmRequest(
            OwnerId: ownerId,
            Name: "Görev Test Sahası",
            Latitude: 37.87,
            Longitude: 32.49,
            SizeInHectares: 8.0,
            IrrigationMethod: IrrigationMethod.Drip,
            InitialCropType: CropType.Corn,
            InitialPlantedAt: new DateOnly(2026, 4, 1)
        );

        var createResponse = await _client.PostAsJsonAsync("/api/v1/farms", createRequest, CustomWebApplicationFactory.JsonOptions);
        createResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        var createResult = await createResponse.Content.ReadFromJsonAsync<Dictionary<string, Guid>>(CustomWebApplicationFactory.JsonOptions);
        var farmId = createResult!["id"];

        // 2. Query Daily Tasks for farm (triggers TaskEngine)
        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        var getTasksRequest = new HttpRequestMessage(HttpMethod.Get, $"/api/v1/farms/{farmId}/tasks?date={today:yyyy-MM-dd}");
        getTasksRequest.Headers.Add("X-User-Id", ownerId.ToString());

        var getTasksResponse = await _client.SendAsync(getTasksRequest);
        getTasksResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        var dailyTasks = await getTasksResponse.Content.ReadFromJsonAsync<DailyTaskListDto>(CustomWebApplicationFactory.JsonOptions);
        dailyTasks.Should().NotBeNull();
        dailyTasks!.Items.Should().NotBeEmpty();

        var firstTask = dailyTasks.Items.First();
        firstTask.Status.Should().Be(TaskStatus.New);

        // 3. Complete the task
        var completeRequest = new CompleteTaskApiRequest(
            UserId: ownerId,
            Role: UserRole.Farmer,
            Note: "Saha kontrolü yapıldı, yapraklar sağlıklı",
            PhotoUrl: null
        );

        var completeResponse = await _client.PostAsJsonAsync($"/api/v1/tasks/{firstTask.Id}/complete", completeRequest, CustomWebApplicationFactory.JsonOptions);
        completeResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        var completedTask = await completeResponse.Content.ReadFromJsonAsync<TaskDto>(CustomWebApplicationFactory.JsonOptions);
        completedTask.Should().NotBeNull();
        completedTask!.Status.Should().Be(TaskStatus.Completed);
    }
}
