using System.Net;
using System.Net.Http.Json;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Moq;
using TarlaAsistani.API.Endpoints;
using TarlaAsistani.Application.Common.Interfaces;
using TarlaAsistani.Application.Features.Tasks.DTOs;
using TarlaAsistani.Domain.Entities;
using TarlaAsistani.Domain.Enums;
using TarlaAsistani.Infrastructure.Persistence;
using TaskStatus = TarlaAsistani.Domain.Enums.TaskStatus;

namespace TarlaAsistani.IntegrationTests;

public class TaskEndpointsIntegrationTests : IClassFixture<CustomWebApplicationFactory>
{
    private readonly HttpClient _client;
    private readonly CustomWebApplicationFactory _factory;

    public TaskEndpointsIntegrationTests(CustomWebApplicationFactory factory)
    {
        _factory = factory;
        _client = factory.CreateClient();
    }

    [Fact]
    public async Task CreateFarmAndGetDailyTasks_ShouldAutoGenerateDailyCheckTasks()
    {
        // 1. Create Farm with active crop period
        var ownerId = Guid.NewGuid();
        var createRequest = new CreateFarmRequest(
            OwnerId: ownerId,
            Name: "Görev Test Sahası",
            Latitude: 37.87,
            Longitude: 32.49,
            SizeInHectares: 8.0,
            IrrigationMethod: IrrigationMethod.Drip,
            InitialCropType: CropType.Corn,
            InitialPlantedAt: new DateOnly(2026, 4, 1)
        );

        var createResponse = await _client.PostAsJsonAsync("/api/v1/farms", createRequest, CustomWebApplicationFactory.JsonOptions);
        createResponse.StatusCode.Should().Be(HttpStatusCode.Created);
        var createResult = await createResponse.Content.ReadFromJsonAsync<Dictionary<string, Guid>>(CustomWebApplicationFactory.JsonOptions);
        var farmId = createResult!["id"];

        // 2. Query Daily Tasks for farm (triggers TaskEngine)
        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        var getTasksRequest = new HttpRequestMessage(HttpMethod.Get, $"/api/v1/farms/{farmId}/tasks?date={today:yyyy-MM-dd}");
        getTasksRequest.Headers.Add("X-User-Id", ownerId.ToString());

        var getTasksResponse = await _client.SendAsync(getTasksRequest);
        getTasksResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        var dailyTasks = await getTasksResponse.Content.ReadFromJsonAsync<DailyTaskListDto>(CustomWebApplicationFactory.JsonOptions);
        dailyTasks.Should().NotBeNull();
        dailyTasks!.Items.Should().NotBeEmpty();

        var firstTask = dailyTasks.Items.First();
        firstTask.Status.Should().Be(TaskStatus.New);

        // 3. Complete the task
        var completeRequest = new CompleteTaskApiRequest(
            UserId: ownerId,
            Role: UserRole.Farmer,
            Note: "Saha kontrolü yapıldı, yapraklar sağlıklı",
            PhotoUrl: null
        );

        var completeResponse = await _client.PostAsJsonAsync($"/api/v1/tasks/{firstTask.Id}/complete", completeRequest, CustomWebApplicationFactory.JsonOptions);
        completeResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        var completedTask = await completeResponse.Content.ReadFromJsonAsync<TaskDto>(CustomWebApplicationFactory.JsonOptions);
        completedTask.Should().NotBeNull();
        completedTask!.Status.Should().Be(TaskStatus.Completed);
    }

    [Fact]
    public async Task FarmerCanCreateManualTaskForOwnedFarm()
    {
        var ownerId = Guid.NewGuid();
        using (var scope = _factory.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
            db.Users.Add(new User
            {
                Id = ownerId,
                PhoneNumber = "+905550000001",
                Role = UserRole.Farmer,
                AccountStatus = AccountStatus.Active,
            });
            await db.SaveChangesAsync();
        }
        var farmResponse = await _client.PostAsJsonAsync(
            "/api/v1/farms",
            new CreateFarmRequest(
                ownerId,
                "Çiftçi Görev Tarlası",
                39.0,
                32.0,
                2,
                null,
                CropType.Wheat,
                new DateOnly(2026, 4, 1)),
            CustomWebApplicationFactory.JsonOptions);
        var farm = await farmResponse.Content.ReadFromJsonAsync<Dictionary<string, Guid>>(
            CustomWebApplicationFactory.JsonOptions);

        var request = new HttpRequestMessage(
            HttpMethod.Post,
            $"/api/v1/farms/{farm!["id"]}/tasks");
        request.Headers.Add("X-User-Id", ownerId.ToString());
        request.Headers.Add("X-User-Role", "Farmer");
        request.Content = JsonContent.Create(
            new CreateExpertTaskApiRequest(
                null,
                "Sulama yap",
                "Akşam sulama",
                "Çiftçi tarafından planlandı",
                TaskPriority.Medium,
                TaskConfidence.High,
                DateOnly.FromDateTime(DateTime.UtcNow.AddDays(1)),
                null),
            options: CustomWebApplicationFactory.JsonOptions);

        var response = await _client.SendAsync(request);
        var responseBody = await response.Content.ReadAsStringAsync();
        response.StatusCode.Should().Be(HttpStatusCode.Created, responseBody);
        var task = await response.Content.ReadFromJsonAsync<TaskDto>(
            CustomWebApplicationFactory.JsonOptions);
        task!.Source.Should().Be(TaskSource.Manual);

        var listRequest = new HttpRequestMessage(
            HttpMethod.Get,
            $"/api/v1/farms/{farm["id"]}/tasks/all");
        listRequest.Headers.Add("X-User-Id", ownerId.ToString());
        listRequest.Headers.Add("X-User-Role", "Farmer");
        var listResponse = await _client.SendAsync(listRequest);
        listResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        var tasks = await listResponse.Content.ReadFromJsonAsync<List<TaskDto>>(
            CustomWebApplicationFactory.JsonOptions);
        tasks.Should().ContainSingle(item => item.Id == task.Id);
    }

    [Fact]
    public async Task ListDailyTasks_WithMultipleCandidatesAndCriticalAlert_ShouldRankAndLimitCorrectly()
    {
        // 1. Arrange: Create user and farm
        var ownerId = Guid.NewGuid();
        var farmId = Guid.NewGuid();
        var today = DateOnly.FromDateTime(DateTime.UtcNow);

        using (var scope = _factory.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
            db.Users.Add(new User
            {
                Id = ownerId,
                PhoneNumber = "+905550000002",
                Role = UserRole.Farmer,
                AccountStatus = AccountStatus.Active,
            });

            db.Farms.Add(new Farm
            {
                Id = farmId,
                OwnerId = ownerId,
                Name = "Sıralama Test Sahası",
                SizeInHectares = 10,
                IrrigationMethod = IrrigationMethod.Drip,
                CreatedAtUtc = DateTime.UtcNow,
                UpdatedAtUtc = DateTime.UtcNow
            });

            // 1 Critical Weather Alert
            db.FarmTasks.Add(new FarmTask
            {
                Id = Guid.NewGuid(),
                FarmId = farmId,
                Title = "Don uyarısı",
                Description = "Don riski bekleniyor",
                Reason = "Hava tahmininde don riski",
                Priority = TaskPriority.Critical,
                Source = TaskSource.Weather,
                Status = TaskStatus.New,
                DueDate = today,
                DedupeKey = "cw-1",
                CreatedAtUtc = DateTime.UtcNow
            });

            // 5 Active regular tasks with different priorities and sources
            db.FarmTasks.Add(new FarmTask
            {
                Id = Guid.NewGuid(),
                FarmId = farmId,
                Title = "Uzman yaprak kontrolü",
                Description = "Yaprakları kontrol et",
                Reason = "Uzman tavsiyesi",
                Priority = TaskPriority.High,
                Source = TaskSource.Expert,
                Status = TaskStatus.New,
                DueDate = today,
                DedupeKey = "reg-expert-high",
                CreatedAtUtc = DateTime.UtcNow
            });

            db.FarmTasks.Add(new FarmTask
            {
                Id = Guid.NewGuid(),
                FarmId = farmId,
                Title = "Acil damlama sulama",
                Description = "Sulama yap",
                Reason = "Su ihtiyacı",
                Priority = TaskPriority.High,
                Source = TaskSource.CropCalendar,
                Status = TaskStatus.New,
                DueDate = today,
                DedupeKey = "reg-crop-high",
                CreatedAtUtc = DateTime.UtcNow
            });

            db.FarmTasks.Add(new FarmTask
            {
                Id = Guid.NewGuid(),
                FarmId = farmId,
                Title = "Gübreleme yapınız",
                Description = "Üst gübreleme",
                Reason = "Gelişim dönemi",
                Priority = TaskPriority.Medium,
                Source = TaskSource.System,
                Status = TaskStatus.New,
                DueDate = today,
                DedupeKey = "reg-sys-med",
                CreatedAtUtc = DateTime.UtcNow
            });

            db.FarmTasks.Add(new FarmTask
            {
                Id = Guid.NewGuid(),
                FarmId = farmId,
                Title = "Uzman genel kontrol",
                Description = "Haftalık kontrol",
                Reason = "Genel gözlem",
                Priority = TaskPriority.Low,
                Source = TaskSource.Expert,
                Status = TaskStatus.New,
                DueDate = today,
                DedupeKey = "reg-expert-low",
                CreatedAtUtc = DateTime.UtcNow
            });

            db.FarmTasks.Add(new FarmTask
            {
                Id = Guid.NewGuid(),
                FarmId = farmId,
                Title = "Çiftçi el aletleri kontrolü",
                Description = "Aletleri temizle",
                Reason = "Bakım",
                Priority = TaskPriority.Low,
                Source = TaskSource.Manual,
                Status = TaskStatus.New,
                DueDate = today,
                DedupeKey = "reg-man-low",
                CreatedAtUtc = DateTime.UtcNow
            });

            // 1 Overdue task (DueDate in past)
            db.FarmTasks.Add(new FarmTask
            {
                Id = Guid.NewGuid(),
                FarmId = farmId,
                Title = "Geçmiş kontrol görevi",
                Description = "Geçmiş iş",
                Reason = "Zamanı geçmiş",
                Priority = TaskPriority.High,
                Source = TaskSource.CropCalendar,
                Status = TaskStatus.New,
                DueDate = today.AddDays(-3),
                DedupeKey = "overdue-1",
                CreatedAtUtc = DateTime.UtcNow.AddDays(-3)
            });

            await db.SaveChangesAsync();
        }

        // 2. Act: Send GET /api/v1/farms/{farmId}/tasks
        var request = new HttpRequestMessage(HttpMethod.Get, $"/api/v1/farms/{farmId}/tasks?date={today:yyyy-MM-dd}");
        request.Headers.Add("X-User-Id", ownerId.ToString());
        request.Headers.Add("X-User-Role", "Farmer");

        var response = await _client.SendAsync(request);
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        var result = await response.Content.ReadFromJsonAsync<DailyTaskListDto>(CustomWebApplicationFactory.JsonOptions);

        // 3. Assert
        result.Should().NotBeNull();
        result!.CriticalWeatherAlerts.Should().HaveCount(1);
        result.CriticalWeatherAlerts.First().Title.Should().Be("Don uyarısı");

        result.Items.Should().HaveCount(3);
        // Correct order: High Expert > High CropCalendar > Medium System
        result.Items[0].Title.Should().Be("Uzman yaprak kontrolü");
        result.Items[1].Title.Should().Be("Acil damlama sulama");
        result.Items[2].Title.Should().Be("Gübreleme yapınız");

        // Items should not include critical weather or low priority tasks
        result.Items.Should().NotContain(i => i.Title == "Don uyarısı");
        result.Items.Should().NotContain(i => i.Title == "Uzman genel kontrol");
        result.Items.Should().NotContain(i => i.Title == "Çiftçi el aletleri kontrolü");
        result.Items.Should().NotContain(i => i.Title == "Geçmiş kontrol görevi");

        // Overdue list should contain the past task
        result.Overdue.Should().ContainSingle(o => o.Title == "Geçmiş kontrol görevi");
    }

    [Fact]
    public async Task SuggestionAdvisoryId_CanActuallyBeApplied()
    {
        // 1. Arrange: Create user and farm
        var ownerId = Guid.NewGuid();
        var farmId = Guid.NewGuid();
        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        var alternativeDate = today.AddDays(1);

        using (var scope = _factory.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
            db.Users.Add(new User
            {
                Id = ownerId,
                PhoneNumber = $"+90555{Random.Shared.Next(1000000, 9999999)}",
                Role = UserRole.Farmer,
                AccountStatus = AccountStatus.Active,
            });

            db.Farms.Add(new Farm
            {
                Id = farmId,
                OwnerId = ownerId,
                Name = "İlaçlama Test Tarlası",
                Latitude = 38.0,
                Longitude = 32.0,
                SizeInHectares = 5,
                IrrigationMethod = IrrigationMethod.Drip,
                CreatedAtUtc = DateTime.UtcNow,
                UpdatedAtUtc = DateTime.UtcNow
            });

            // Add a planned spraying task for today
            db.FarmTasks.Add(new FarmTask
            {
                Id = Guid.NewGuid(),
                FarmId = farmId,
                Title = "Zararlı böceklere karşı ilaçlama yap",
                Description = "İlaçlama rüzgarsız havada uygulanmalı",
                Reason = "Böcek popülasyonu arttı",
                Priority = TaskPriority.High,
                Source = TaskSource.System,
                Status = TaskStatus.Planned,
                DueDate = today,
                DedupeKey = $"spray-task-{Guid.NewGuid():N}",
                CreatedAtUtc = DateTime.UtcNow
            });

            await db.SaveChangesAsync();
        }

        // Mock weather: today has high wind (25 km/h), tomorrow has calm wind (8 km/h)
        var points = new List<WeatherPoint>
        {
            new(DateTime.UtcNow, TemperatureC: 22, PrecipitationProbability: 0, PrecipitationMm: 0, WindSpeedKmh: 25),
            new(DateTime.UtcNow.AddDays(1), TemperatureC: 20, PrecipitationProbability: 0, PrecipitationMm: 0, WindSpeedKmh: 8),
            new(DateTime.UtcNow.AddDays(2), TemperatureC: 21, PrecipitationProbability: 0, PrecipitationMm: 0, WindSpeedKmh: 8)
        };

        _factory.MockWeatherProvider
            .Setup(w => w.ForecastAsync(It.IsAny<double>(), It.IsAny<double>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(points);
        _factory.MockWeatherProvider
            .Setup(w => w.GetWeatherAsync(It.IsAny<double>(), It.IsAny<double>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new WeatherForecastData(points));

        // 2. Act: Call GET /api/v1/farms/{farmId}/tasks
        var getTasksRequest = new HttpRequestMessage(HttpMethod.Get, $"/api/v1/farms/{farmId}/tasks?date={today:yyyy-MM-dd}");
        getTasksRequest.Headers.Add("X-User-Id", ownerId.ToString());
        getTasksRequest.Headers.Add("X-User-Role", "Farmer");

        var getTasksResponse = await _client.SendAsync(getTasksRequest);
        getTasksResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        var dailyTasks = await getTasksResponse.Content.ReadFromJsonAsync<DailyTaskListDto>(CustomWebApplicationFactory.JsonOptions);
        dailyTasks.Should().NotBeNull();
        dailyTasks!.Items.Should().NotBeEmpty();

        var sprayingTask = dailyTasks.Items.First(t => t.Title.Contains("ilaçlama", StringComparison.OrdinalIgnoreCase));
        sprayingTask.WeatherPostponeSuggestion.Should().NotBeNull();
        var suggestion = sprayingTask.WeatherPostponeSuggestion!;

        suggestion.CanApply.Should().BeTrue();
        suggestion.AdvisoryId.Should().NotBeNull();
        suggestion.RecommendedDate.Should().Be(alternativeDate);
        suggestion.IsWeatherStale.Should().BeFalse();

        // 3. Act: Apply the advisory via POST /api/v1/ai/advisories/{id}/apply
        var applyRequest = new HttpRequestMessage(HttpMethod.Post, $"/api/v1/ai/advisories/{suggestion.AdvisoryId}/apply");
        applyRequest.Headers.Add("X-User-Id", ownerId.ToString());

        var applyResponse = await _client.SendAsync(applyRequest);
        applyResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        // 4. Assert: FarmTask.DueDate is updated to RecommendedDate, advisory is marked IsApplied
        using (var scope = _factory.Services.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
            var updatedTask = await db.FarmTasks.FirstAsync(t => t.Id == sprayingTask.Id);
            updatedTask.DueDate.Should().Be(alternativeDate);

            var updatedAdvisory = await db.ProactiveAdvisories.FirstAsync(a => a.Id == suggestion.AdvisoryId);
            updatedAdvisory.IsApplied.Should().BeTrue();
        }

        // 5. Assert via GET contract: Query tasks on target new date (alternativeDate); task must appear with DueDate == alternativeDate
        var getNewDateTasksRequest = new HttpRequestMessage(HttpMethod.Get, $"/api/v1/farms/{farmId}/tasks?date={alternativeDate:yyyy-MM-dd}");
        getNewDateTasksRequest.Headers.Add("X-User-Id", ownerId.ToString());
        getNewDateTasksRequest.Headers.Add("X-User-Role", "Farmer");

        var getNewDateResponse = await _client.SendAsync(getNewDateTasksRequest);
        getNewDateResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        var newDateTasks = await getNewDateResponse.Content.ReadFromJsonAsync<DailyTaskListDto>(CustomWebApplicationFactory.JsonOptions);
        newDateTasks.Should().NotBeNull();
        newDateTasks!.Items.Should().Contain(t => t.Id == sprayingTask.Id && t.DueDate == alternativeDate);
    }
}
